language: nix
env:
  - NIXPKGS_CHANNEL=nixos-20.03
  - NIXPKGS_CHANNEL=nixos-unstable

# By building the tests, we also build yarn2nix itself.
script:
  # delete builtins.fetchGit cache, because it makes tests irreproducible:
  # test may pass with cache present, but in reality it should fail with "Cannot find revision" error
  - rm -rdf ~/.cache/nix/git

  - ./run-tests.sh
